# Generated by Django 5.1.4 on 2024-12-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=500)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('balance', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
