# Generated by Django 5.1.4 on 2024-12-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_syndicat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residence',
            old_name='adress',
            new_name='address',
        ),
    ]
